apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-demo
  labels:
    app: gke-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-demo
  template:
    metadata:
      labels:
        app: gke-demo
    spec:
    
      nodeSelector:
        pool: application
      containers:
      - name: gke-demo
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gke-demo
spec:
  selector:
    app: gke-demo
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP