persistence:
  enabled: true
  size: 5Gi


adminUser: admin
adminPassword: StrongPassword123!


datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      access: proxy
      isDefault: true


dashboards:
  default:
    pod-restarts:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": 8,
          "links": [],
          "panels": [
            {
              "alert": {
                "alertRuleTags": {},
                "conditions": [
                  {
                    "evaluator": {
                      "params": [
                        0
                      ],
                      "type": "gt"
                    },
                    "operator": {
                      "type": "and"
                    },
                    "query": {
                      "params": [
                        "A",
                        "5m",
                        "now"
                      ]
                    },
                    "reducer": {
                      "params": [],
                      "type": "diff"
                    },
                    "type": "query"
                  }
                ],
                "executionErrorState": "alerting",
                "for": "5m",
                "frequency": "1m",
                "handler": 1,
                "name": "Pod Restart Alert",
                "noDataState": "no_data",
                "notifications": []
              },
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Prometheus",
              "description": "Monitors pod restarts",
              "fieldConfig": {
                "defaults": {
                  "custom": {}
                },
                "overrides": []
              },
              "fill": 1,
              "fillGradient": 0,
              "gridPos": {
                "h": 8,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "hiddenSeries": false,
              "id": 2,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
              },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": {
                "alertThreshold": true
              },
              "percentage": false,
              "pluginVersion": "7.2.0",
              "pointradius": 2,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "expr": "kube_pod_container_status_restarts_total",
                  "interval": "",
                  "legendFormat": "{{pod}}",
                  "refId": "A"
                }
              ],
              "thresholds": [
                {
                  "colorMode": "critical",
                  "fill": true,
                  "line": true,
                  "op": "gt",
                  "value": 0
                }
              ],
              "timeFrom": null,
              "timeRegions": [],
              "timeShift": null,
              "title": "Pod Restarts",
              "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
              },
              "yaxes": [
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                },
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                }
              ],
              "yaxis": {
                "align": false,
                "alignLevel": null
              }
            }
          ],
          "schemaVersion": 26,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-6h",
            "to": "now"
          },
          "timepicker": {},
          "timezone": "",
          "title": "Pod Restarts",
          "uid": "pod-restarts",
          "version": 1
        }

alerting:
  enabled: true